// Code generated by mockery v2.53.6. DO NOT EDIT.

package authorizationcode

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/tniah/authlib/models"

	requests "github.com/tniah/authlib/requests"
)

// MockAuthCodeProcessor is an autogenerated mock type for the AuthCodeProcessor type
type MockAuthCodeProcessor struct {
	mock.Mock
}

type MockAuthCodeProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthCodeProcessor) EXPECT() *MockAuthCodeProcessor_Expecter {
	return &MockAuthCodeProcessor_Expecter{mock: &_m.Mock}
}

// ProcessAuthorizationCode provides a mock function with given fields: r, authCode, params
func (_m *MockAuthCodeProcessor) ProcessAuthorizationCode(r *requests.AuthorizationRequest, authCode models.AuthorizationCode, params map[string]interface{}) error {
	ret := _m.Called(r, authCode, params)

	if len(ret) == 0 {
		panic("no return value specified for ProcessAuthorizationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*requests.AuthorizationRequest, models.AuthorizationCode, map[string]interface{}) error); ok {
		r0 = rf(r, authCode, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthCodeProcessor_ProcessAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessAuthorizationCode'
type MockAuthCodeProcessor_ProcessAuthorizationCode_Call struct {
	*mock.Call
}

// ProcessAuthorizationCode is a helper method to define mock.On call
//   - r *requests.AuthorizationRequest
//   - authCode models.AuthorizationCode
//   - params map[string]interface{}
func (_e *MockAuthCodeProcessor_Expecter) ProcessAuthorizationCode(r interface{}, authCode interface{}, params interface{}) *MockAuthCodeProcessor_ProcessAuthorizationCode_Call {
	return &MockAuthCodeProcessor_ProcessAuthorizationCode_Call{Call: _e.mock.On("ProcessAuthorizationCode", r, authCode, params)}
}

func (_c *MockAuthCodeProcessor_ProcessAuthorizationCode_Call) Run(run func(r *requests.AuthorizationRequest, authCode models.AuthorizationCode, params map[string]interface{})) *MockAuthCodeProcessor_ProcessAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*requests.AuthorizationRequest), args[1].(models.AuthorizationCode), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockAuthCodeProcessor_ProcessAuthorizationCode_Call) Return(_a0 error) *MockAuthCodeProcessor_ProcessAuthorizationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthCodeProcessor_ProcessAuthorizationCode_Call) RunAndReturn(run func(*requests.AuthorizationRequest, models.AuthorizationCode, map[string]interface{}) error) *MockAuthCodeProcessor_ProcessAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthCodeProcessor creates a new instance of MockAuthCodeProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthCodeProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthCodeProcessor {
	mock := &MockAuthCodeProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
