// Code generated by mockery v2.53.6. DO NOT EDIT.

package authorizationcode

import (
	mock "github.com/stretchr/testify/mock"
	requests "github.com/tniah/authlib/requests"
)

// MockAuthorizationRequestValidator is an autogenerated mock type for the AuthorizationRequestValidator type
type MockAuthorizationRequestValidator struct {
	mock.Mock
}

type MockAuthorizationRequestValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizationRequestValidator) EXPECT() *MockAuthorizationRequestValidator_Expecter {
	return &MockAuthorizationRequestValidator_Expecter{mock: &_m.Mock}
}

// ValidateAuthorizationRequest provides a mock function with given fields: r
func (_m *MockAuthorizationRequestValidator) ValidateAuthorizationRequest(r *requests.AuthorizationRequest) error {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAuthorizationRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*requests.AuthorizationRequest) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAuthorizationRequest'
type MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call struct {
	*mock.Call
}

// ValidateAuthorizationRequest is a helper method to define mock.On call
//   - r *requests.AuthorizationRequest
func (_e *MockAuthorizationRequestValidator_Expecter) ValidateAuthorizationRequest(r interface{}) *MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call {
	return &MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call{Call: _e.mock.On("ValidateAuthorizationRequest", r)}
}

func (_c *MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call) Run(run func(r *requests.AuthorizationRequest)) *MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*requests.AuthorizationRequest))
	})
	return _c
}

func (_c *MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call) Return(_a0 error) *MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call) RunAndReturn(run func(*requests.AuthorizationRequest) error) *MockAuthorizationRequestValidator_ValidateAuthorizationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorizationRequestValidator creates a new instance of MockAuthorizationRequestValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizationRequestValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizationRequestValidator {
	mock := &MockAuthorizationRequestValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
