// Code generated by mockery v2.53.6. DO NOT EDIT.

package authorizationcode

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tniah/authlib/models"

	requests "github.com/tniah/authlib/requests"
)

// MockAuthCodeManager is an autogenerated mock type for the AuthCodeManager type
type MockAuthCodeManager struct {
	mock.Mock
}

type MockAuthCodeManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthCodeManager) EXPECT() *MockAuthCodeManager_Expecter {
	return &MockAuthCodeManager_Expecter{mock: &_m.Mock}
}

// DeleteByCode provides a mock function with given fields: ctx, code
func (_m *MockAuthCodeManager) DeleteByCode(ctx context.Context, code string) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthCodeManager_DeleteByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCode'
type MockAuthCodeManager_DeleteByCode_Call struct {
	*mock.Call
}

// DeleteByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockAuthCodeManager_Expecter) DeleteByCode(ctx interface{}, code interface{}) *MockAuthCodeManager_DeleteByCode_Call {
	return &MockAuthCodeManager_DeleteByCode_Call{Call: _e.mock.On("DeleteByCode", ctx, code)}
}

func (_c *MockAuthCodeManager_DeleteByCode_Call) Run(run func(ctx context.Context, code string)) *MockAuthCodeManager_DeleteByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthCodeManager_DeleteByCode_Call) Return(_a0 error) *MockAuthCodeManager_DeleteByCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthCodeManager_DeleteByCode_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthCodeManager_DeleteByCode_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function with given fields: authCode, r
func (_m *MockAuthCodeManager) Generate(authCode models.AuthorizationCode, r *requests.AuthorizationRequest) error {
	ret := _m.Called(authCode, r)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.AuthorizationCode, *requests.AuthorizationRequest) error); ok {
		r0 = rf(authCode, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthCodeManager_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockAuthCodeManager_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - authCode models.AuthorizationCode
//   - r *requests.AuthorizationRequest
func (_e *MockAuthCodeManager_Expecter) Generate(authCode interface{}, r interface{}) *MockAuthCodeManager_Generate_Call {
	return &MockAuthCodeManager_Generate_Call{Call: _e.mock.On("Generate", authCode, r)}
}

func (_c *MockAuthCodeManager_Generate_Call) Run(run func(authCode models.AuthorizationCode, r *requests.AuthorizationRequest)) *MockAuthCodeManager_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.AuthorizationCode), args[1].(*requests.AuthorizationRequest))
	})
	return _c
}

func (_c *MockAuthCodeManager_Generate_Call) Return(_a0 error) *MockAuthCodeManager_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthCodeManager_Generate_Call) RunAndReturn(run func(models.AuthorizationCode, *requests.AuthorizationRequest) error) *MockAuthCodeManager_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function with no fields
func (_m *MockAuthCodeManager) New() models.AuthorizationCode {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 models.AuthorizationCode
	if rf, ok := ret.Get(0).(func() models.AuthorizationCode); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.AuthorizationCode)
		}
	}

	return r0
}

// MockAuthCodeManager_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockAuthCodeManager_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *MockAuthCodeManager_Expecter) New() *MockAuthCodeManager_New_Call {
	return &MockAuthCodeManager_New_Call{Call: _e.mock.On("New")}
}

func (_c *MockAuthCodeManager_New_Call) Run(run func()) *MockAuthCodeManager_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthCodeManager_New_Call) Return(_a0 models.AuthorizationCode) *MockAuthCodeManager_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthCodeManager_New_Call) RunAndReturn(run func() models.AuthorizationCode) *MockAuthCodeManager_New_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByCode provides a mock function with given fields: ctx, code
func (_m *MockAuthCodeManager) QueryByCode(ctx context.Context, code string) (models.AuthorizationCode, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for QueryByCode")
	}

	var r0 models.AuthorizationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.AuthorizationCode, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.AuthorizationCode); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.AuthorizationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthCodeManager_QueryByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByCode'
type MockAuthCodeManager_QueryByCode_Call struct {
	*mock.Call
}

// QueryByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockAuthCodeManager_Expecter) QueryByCode(ctx interface{}, code interface{}) *MockAuthCodeManager_QueryByCode_Call {
	return &MockAuthCodeManager_QueryByCode_Call{Call: _e.mock.On("QueryByCode", ctx, code)}
}

func (_c *MockAuthCodeManager_QueryByCode_Call) Run(run func(ctx context.Context, code string)) *MockAuthCodeManager_QueryByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthCodeManager_QueryByCode_Call) Return(_a0 models.AuthorizationCode, _a1 error) *MockAuthCodeManager_QueryByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthCodeManager_QueryByCode_Call) RunAndReturn(run func(context.Context, string) (models.AuthorizationCode, error)) *MockAuthCodeManager_QueryByCode_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, code
func (_m *MockAuthCodeManager) Save(ctx context.Context, code models.AuthorizationCode) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AuthorizationCode) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthCodeManager_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAuthCodeManager_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - code models.AuthorizationCode
func (_e *MockAuthCodeManager_Expecter) Save(ctx interface{}, code interface{}) *MockAuthCodeManager_Save_Call {
	return &MockAuthCodeManager_Save_Call{Call: _e.mock.On("Save", ctx, code)}
}

func (_c *MockAuthCodeManager_Save_Call) Run(run func(ctx context.Context, code models.AuthorizationCode)) *MockAuthCodeManager_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AuthorizationCode))
	})
	return _c
}

func (_c *MockAuthCodeManager_Save_Call) Return(_a0 error) *MockAuthCodeManager_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthCodeManager_Save_Call) RunAndReturn(run func(context.Context, models.AuthorizationCode) error) *MockAuthCodeManager_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthCodeManager creates a new instance of MockAuthCodeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthCodeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthCodeManager {
	mock := &MockAuthCodeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
