// Code generated by mockery v2.53.6. DO NOT EDIT.

package authorizationcode

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	models "github.com/tniah/authlib/models"

	types "github.com/tniah/authlib/types"
)

// MockClientManager is an autogenerated mock type for the ClientManager type
type MockClientManager struct {
	mock.Mock
}

type MockClientManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientManager) EXPECT() *MockClientManager_Expecter {
	return &MockClientManager_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: r, authMethods, endpointName
func (_m *MockClientManager) Authenticate(r *http.Request, authMethods map[types.ClientAuthMethod]bool, endpointName string) (models.Client, error) {
	ret := _m.Called(r, authMethods, endpointName)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 models.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request, map[types.ClientAuthMethod]bool, string) (models.Client, error)); ok {
		return rf(r, authMethods, endpointName)
	}
	if rf, ok := ret.Get(0).(func(*http.Request, map[types.ClientAuthMethod]bool, string) models.Client); ok {
		r0 = rf(r, authMethods, endpointName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request, map[types.ClientAuthMethod]bool, string) error); ok {
		r1 = rf(r, authMethods, endpointName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientManager_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockClientManager_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - r *http.Request
//   - authMethods map[types.ClientAuthMethod]bool
//   - endpointName string
func (_e *MockClientManager_Expecter) Authenticate(r interface{}, authMethods interface{}, endpointName interface{}) *MockClientManager_Authenticate_Call {
	return &MockClientManager_Authenticate_Call{Call: _e.mock.On("Authenticate", r, authMethods, endpointName)}
}

func (_c *MockClientManager_Authenticate_Call) Run(run func(r *http.Request, authMethods map[types.ClientAuthMethod]bool, endpointName string)) *MockClientManager_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request), args[1].(map[types.ClientAuthMethod]bool), args[2].(string))
	})
	return _c
}

func (_c *MockClientManager_Authenticate_Call) Return(_a0 models.Client, _a1 error) *MockClientManager_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientManager_Authenticate_Call) RunAndReturn(run func(*http.Request, map[types.ClientAuthMethod]bool, string) (models.Client, error)) *MockClientManager_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByClientID provides a mock function with given fields: ctx, clientID
func (_m *MockClientManager) QueryByClientID(ctx context.Context, clientID string) (models.Client, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByClientID")
	}

	var r0 models.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Client, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Client); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientManager_QueryByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByClientID'
type MockClientManager_QueryByClientID_Call struct {
	*mock.Call
}

// QueryByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockClientManager_Expecter) QueryByClientID(ctx interface{}, clientID interface{}) *MockClientManager_QueryByClientID_Call {
	return &MockClientManager_QueryByClientID_Call{Call: _e.mock.On("QueryByClientID", ctx, clientID)}
}

func (_c *MockClientManager_QueryByClientID_Call) Run(run func(ctx context.Context, clientID string)) *MockClientManager_QueryByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientManager_QueryByClientID_Call) Return(_a0 models.Client, _a1 error) *MockClientManager_QueryByClientID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientManager_QueryByClientID_Call) RunAndReturn(run func(context.Context, string) (models.Client, error)) *MockClientManager_QueryByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientManager creates a new instance of MockClientManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientManager {
	mock := &MockClientManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
