// Code generated by mockery v2.53.6. DO NOT EDIT.

package authorizationcode

import (
	mock "github.com/stretchr/testify/mock"
	requests "github.com/tniah/authlib/requests"
)

// MockConsentRequestValidator is an autogenerated mock type for the ConsentRequestValidator type
type MockConsentRequestValidator struct {
	mock.Mock
}

type MockConsentRequestValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsentRequestValidator) EXPECT() *MockConsentRequestValidator_Expecter {
	return &MockConsentRequestValidator_Expecter{mock: &_m.Mock}
}

// ValidateConsentRequest provides a mock function with given fields: r
func (_m *MockConsentRequestValidator) ValidateConsentRequest(r *requests.AuthorizationRequest) error {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConsentRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*requests.AuthorizationRequest) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsentRequestValidator_ValidateConsentRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConsentRequest'
type MockConsentRequestValidator_ValidateConsentRequest_Call struct {
	*mock.Call
}

// ValidateConsentRequest is a helper method to define mock.On call
//   - r *requests.AuthorizationRequest
func (_e *MockConsentRequestValidator_Expecter) ValidateConsentRequest(r interface{}) *MockConsentRequestValidator_ValidateConsentRequest_Call {
	return &MockConsentRequestValidator_ValidateConsentRequest_Call{Call: _e.mock.On("ValidateConsentRequest", r)}
}

func (_c *MockConsentRequestValidator_ValidateConsentRequest_Call) Run(run func(r *requests.AuthorizationRequest)) *MockConsentRequestValidator_ValidateConsentRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*requests.AuthorizationRequest))
	})
	return _c
}

func (_c *MockConsentRequestValidator_ValidateConsentRequest_Call) Return(_a0 error) *MockConsentRequestValidator_ValidateConsentRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsentRequestValidator_ValidateConsentRequest_Call) RunAndReturn(run func(*requests.AuthorizationRequest) error) *MockConsentRequestValidator_ValidateConsentRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsentRequestValidator creates a new instance of MockConsentRequestValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsentRequestValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsentRequestValidator {
	mock := &MockConsentRequestValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
