// Code generated by mockery v2.53.6. DO NOT EDIT.

package authorizationcode

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tniah/authlib/models"

	requests "github.com/tniah/authlib/requests"
)

// MockUserManager is an autogenerated mock type for the UserManager type
type MockUserManager struct {
	mock.Mock
}

type MockUserManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserManager) EXPECT() *MockUserManager_Expecter {
	return &MockUserManager_Expecter{mock: &_m.Mock}
}

// QueryUserByCode provides a mock function with given fields: ctx, code, r
func (_m *MockUserManager) QueryUserByCode(ctx context.Context, code models.AuthorizationCode, r *requests.TokenRequest) (models.User, error) {
	ret := _m.Called(ctx, code, r)

	if len(ret) == 0 {
		panic("no return value specified for QueryUserByCode")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AuthorizationCode, *requests.TokenRequest) (models.User, error)); ok {
		return rf(ctx, code, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AuthorizationCode, *requests.TokenRequest) models.User); ok {
		r0 = rf(ctx, code, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AuthorizationCode, *requests.TokenRequest) error); ok {
		r1 = rf(ctx, code, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_QueryUserByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryUserByCode'
type MockUserManager_QueryUserByCode_Call struct {
	*mock.Call
}

// QueryUserByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code models.AuthorizationCode
//   - r *requests.TokenRequest
func (_e *MockUserManager_Expecter) QueryUserByCode(ctx interface{}, code interface{}, r interface{}) *MockUserManager_QueryUserByCode_Call {
	return &MockUserManager_QueryUserByCode_Call{Call: _e.mock.On("QueryUserByCode", ctx, code, r)}
}

func (_c *MockUserManager_QueryUserByCode_Call) Run(run func(ctx context.Context, code models.AuthorizationCode, r *requests.TokenRequest)) *MockUserManager_QueryUserByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AuthorizationCode), args[2].(*requests.TokenRequest))
	})
	return _c
}

func (_c *MockUserManager_QueryUserByCode_Call) Return(_a0 models.User, _a1 error) *MockUserManager_QueryUserByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_QueryUserByCode_Call) RunAndReturn(run func(context.Context, models.AuthorizationCode, *requests.TokenRequest) (models.User, error)) *MockUserManager_QueryUserByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserManager creates a new instance of MockUserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserManager {
	mock := &MockUserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
