// Code generated by mockery v2.49.0. DO NOT EDIT.

package rfc6750

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/tniah/authlib/models"
)

// MockRandStringGenerator is an autogenerated mock type for the RandStringGenerator type
type MockRandStringGenerator struct {
	mock.Mock
}

type MockRandStringGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRandStringGenerator) EXPECT() *MockRandStringGenerator_Expecter {
	return &MockRandStringGenerator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: grantType, client
func (_m *MockRandStringGenerator) Execute(grantType string, client models.Client) string {
	ret := _m.Called(grantType, client)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, models.Client) string); ok {
		r0 = rf(grantType, client)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRandStringGenerator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRandStringGenerator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - grantType string
//   - client models.Client
func (_e *MockRandStringGenerator_Expecter) Execute(grantType interface{}, client interface{}) *MockRandStringGenerator_Execute_Call {
	return &MockRandStringGenerator_Execute_Call{Call: _e.mock.On("Execute", grantType, client)}
}

func (_c *MockRandStringGenerator_Execute_Call) Run(run func(grantType string, client models.Client)) *MockRandStringGenerator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(models.Client))
	})
	return _c
}

func (_c *MockRandStringGenerator_Execute_Call) Return(_a0 string) *MockRandStringGenerator_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRandStringGenerator_Execute_Call) RunAndReturn(run func(string, models.Client) string) *MockRandStringGenerator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRandStringGenerator creates a new instance of MockRandStringGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRandStringGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRandStringGenerator {
	mock := &MockRandStringGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
