with-expecter: true
issue-845-fix: True
resolve-type-alias: False
filename: "{{ .InterfaceName | snakecase }}.go"
dir: "mocks/{{ .InterfaceDirRelative }}"
packages:
  github.com/tniah/authlib/models:
    config:
      outpkg: models
    interfaces:
      Client:
      User:
      Token:
  github.com/tniah/authlib/rfc7662:
    config:
      outpkg: rfc7662
    interfaces:
      ClientManager:
      TokenManager:
  github.com/tniah/authlib/rfc9068:
    config:
      outpkg: rfc9068
    interfaces:
      IssuerGenerator:
      ExpiresInGenerator:
      SigningKeyGenerator:
      ExtraClaimGenerator:
      JWTIDGenerator:
