// Code generated by mockery v2.49.0. DO NOT EDIT.

package models

import mock "github.com/stretchr/testify/mock"

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

type MockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUser) EXPECT() *MockUser_Expecter {
	return &MockUser_Expecter{mock: &_m.Mock}
}

// GetUserID provides a mock function with given fields:
func (_m *MockUser) GetUserID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUser_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockUser_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
func (_e *MockUser_Expecter) GetUserID() *MockUser_GetUserID_Call {
	return &MockUser_GetUserID_Call{Call: _e.mock.On("GetUserID")}
}

func (_c *MockUser_GetUserID_Call) Run(run func()) *MockUser_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_GetUserID_Call) Return(_a0 string) *MockUser_GetUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUser_GetUserID_Call) RunAndReturn(run func() string) *MockUser_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
