// Code generated by mockery v2.49.0. DO NOT EDIT.

package rfc9068

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tniah/authlib/models"
)

// MockJWTIDGenerator is an autogenerated mock type for the JWTIDGenerator type
type MockJWTIDGenerator struct {
	mock.Mock
}

type MockJWTIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTIDGenerator) EXPECT() *MockJWTIDGenerator_Expecter {
	return &MockJWTIDGenerator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, grantType, client
func (_m *MockJWTIDGenerator) Execute(ctx context.Context, grantType string, client models.Client) string {
	ret := _m.Called(ctx, grantType, client)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Client) string); ok {
		r0 = rf(ctx, grantType, client)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockJWTIDGenerator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockJWTIDGenerator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - grantType string
//   - client models.Client
func (_e *MockJWTIDGenerator_Expecter) Execute(ctx interface{}, grantType interface{}, client interface{}) *MockJWTIDGenerator_Execute_Call {
	return &MockJWTIDGenerator_Execute_Call{Call: _e.mock.On("Execute", ctx, grantType, client)}
}

func (_c *MockJWTIDGenerator_Execute_Call) Run(run func(ctx context.Context, grantType string, client models.Client)) *MockJWTIDGenerator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Client))
	})
	return _c
}

func (_c *MockJWTIDGenerator_Execute_Call) Return(_a0 string) *MockJWTIDGenerator_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJWTIDGenerator_Execute_Call) RunAndReturn(run func(context.Context, string, models.Client) string) *MockJWTIDGenerator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTIDGenerator creates a new instance of MockJWTIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTIDGenerator {
	mock := &MockJWTIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
