// Code generated by mockery v2.49.0. DO NOT EDIT.

package ropc

import (
	mock "github.com/stretchr/testify/mock"
	requests "github.com/tniah/authlib/requests"
)

// MockTokenRequestValidator is an autogenerated mock type for the TokenRequestValidator type
type MockTokenRequestValidator struct {
	mock.Mock
}

type MockTokenRequestValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRequestValidator) EXPECT() *MockTokenRequestValidator_Expecter {
	return &MockTokenRequestValidator_Expecter{mock: &_m.Mock}
}

// ValidateTokenRequest provides a mock function with given fields: r
func (_m *MockTokenRequestValidator) ValidateTokenRequest(r *requests.TokenRequest) error {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTokenRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*requests.TokenRequest) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRequestValidator_ValidateTokenRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTokenRequest'
type MockTokenRequestValidator_ValidateTokenRequest_Call struct {
	*mock.Call
}

// ValidateTokenRequest is a helper method to define mock.On call
//   - r *requests.TokenRequest
func (_e *MockTokenRequestValidator_Expecter) ValidateTokenRequest(r interface{}) *MockTokenRequestValidator_ValidateTokenRequest_Call {
	return &MockTokenRequestValidator_ValidateTokenRequest_Call{Call: _e.mock.On("ValidateTokenRequest", r)}
}

func (_c *MockTokenRequestValidator_ValidateTokenRequest_Call) Run(run func(r *requests.TokenRequest)) *MockTokenRequestValidator_ValidateTokenRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*requests.TokenRequest))
	})
	return _c
}

func (_c *MockTokenRequestValidator_ValidateTokenRequest_Call) Return(_a0 error) *MockTokenRequestValidator_ValidateTokenRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRequestValidator_ValidateTokenRequest_Call) RunAndReturn(run func(*requests.TokenRequest) error) *MockTokenRequestValidator_ValidateTokenRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRequestValidator creates a new instance of MockTokenRequestValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRequestValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRequestValidator {
	mock := &MockTokenRequestValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
